config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'habits#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :habits
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  has_many :occurences
end

app/models/occurence.rb
class Occurence < ApplicationRecord
    belongs_to :habit
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :habits
  accepts_nested_attributes_for :habits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
	def new
		@habit = Habit.new
	end

	def create
		@habit = Habit.new(habit_params)
		if @habit.save
			redirect_to habits_path, notice: "Habit added."
		else
			redirect_to habits_path, notice: "Error occured."
		end

	end

	def index
		@habits = Habit.all
	end

	private
		def habit_params
			params.require(:habit).permit(:title, :description, :frequency, :difficulty)
		end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/habits/_form.html.erb
<%= form_for @habit do |f| %>
  <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :difficulty %>
        <%= f.range_field :difficulty, in: 1..3, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :frequency %>
        <%= f.range_field :frequency, in: 1..7, class: 'form-control' %>
      </div>

      </div>
      <%= f.submit 'Submit', class: 'btn btn-default' %>
    <% end %>
  </div>

app/views/habits/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Habits</h1>
    <div class="well">
      <ul>
      <%= flash[:notice] %>
        <% @habits.each do |habit| %>
          <% if habit %>
            <li>
            <div class >
              <%= habit.title %><br/>
            </li>
          <% end %>
        <% end %>
      </ul>
      <%= link_to 'Add habit', new_habit_path(@user) %>
    </div>
  </div>
</div>

app/views/habits/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create a new habit</h1>
    <p class="text-center">Pick a new challenge for yourself</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HabitsApp</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top site-header" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <%= link_to '/', class: "navbar-brand" do %>
          <i class="fa fa-group"></i>
          MyHabits
        <% end %>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
          <% else %>
            <%= link_to 'Log In', new_user_session_path, class: "btn btn-default navbar-btn" %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-default navbar-btn" %>
          <% end %>
          </div>
        </div>
      </div>
    </nav>
  </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>